build:
    environment:
        php:
            version: 7.2.0
        redis: false
        mysql: 5.6
checks:
    php: true        
tools:
    php_code_coverage:
        enabled: true

filter:
    excluded_paths: [components/*, classes/mail/*, system/*, vendors/*, theme/*]
