build:
    environment:
        php:
            version: 7.2.0
        redis: false
        mysql: 5.6
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_php_opening_tag: true
        fix_line_ending: true
        fix_doc_comments: false       
tools:
    php_code_coverage:
        enabled: true

filter:
    excluded_paths: [components/*, classes/mail/*, system/*, vendors/*, theme/*]
